{
  "hash": "edd0aef0a5eb401aa12642f1be6d1491",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 2: Who Do We Know the Least About?\"\nsubtitle: \"Measuring uncertainty in American Community Survey data\"\nauthor: \"Frederick Abalo\"\ndate: today\nformat:\n  html:\n    toc: true\n    code-fold: false\nexecute:\n  warning: false\n  message: false\n---\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidycensus)\n```\n:::\n\n\n\n## The question\n\nEvery number the American Community Survey publishes is an estimate drawn from a\nsample, not a count. That means every number comes with a margin of error — a\nstatement about how wrong it might be.\n\nMost people ignore it. In this assignment, you won't.\n\n\n## Choosing what to measure\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_state <- \"CA\"        # two-letter abbreviation, in quotes\nmy_variable <- \"B01002_001\"     # the variable code, in quotes\n```\n:::\n\n\n## Pulling the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- get_acs(\n  geography = \"county\",\n  variables = my_variable,\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\"\n)\n```\n:::\n\n\nLet's look at what came back.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 58  5\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  GEOID NAME                         variable   estimate   moe\n  <chr> <chr>                        <chr>         <dbl> <dbl>\n1 06001 Alameda County, California   B01002_001     38.7   0.2\n2 06003 Alpine County, California    B01002_001     41.1   4.8\n3 06005 Amador County, California    B01002_001     49.9   0.6\n4 06007 Butte County, California     B01002_001     36.3   0.2\n5 06009 Calaveras County, California B01002_001     52     0.7\n6 06011 Colusa County, California    B01002_001     35.7   0.9\n```\n\n\n:::\n:::\n\n\n\nCalifornia has 58 counties and that number matches the number of rows (58) returned by checking the dimensions of the data.\n\n## How big is the margin of error?\n\nA margin of error of 3,000 means something very different for an estimate of 20,000\nthan for an estimate of 200,000. To compare across places, we need it as a\npercentage.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(moe_pct = moe / estimate * 100)\n```\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data %>%\n  arrange(desc(moe_pct)) %>%\n  select(NAME, estimate, moe, moe_pct) %>%\n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   NAME                         estimate   moe moe_pct\n   <chr>                           <dbl> <dbl>   <dbl>\n 1 Alpine County, California        41.1   4.8   11.7 \n 2 Sierra County, California        56     5      8.93\n 3 Mono County, California          40.3   1.8    4.47\n 4 Modoc County, California         49     2.1    4.29\n 5 Colusa County, California        35.7   0.9    2.52\n 6 Del Norte County, California     40.8   0.9    2.21\n 7 Mariposa County, California      51.6   1      1.94\n 8 Trinity County, California       54.8   0.9    1.64\n 9 Lassen County, California        37.8   0.6    1.59\n10 Plumas County, California        52.1   0.8    1.54\n```\n\n\n:::\n:::\n\n\n\nAlpine County is the least reliable county in the dataset, with the highest relative margin of error(moe_pct) at approximately 11.68%.\n\n\n## Sorting counties into reliability categories\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(reliability = case_when(\n    moe_pct < 1  ~ \"High confidence\",\n    moe_pct < 4  ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n\ncount(county_data, reliability)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  reliability         n\n  <chr>           <int>\n1 High confidence    42\n2 Low confidence      4\n3 Moderate           12\n```\n\n\n:::\n:::\n\n\nUsing the original thresholds, 56 counties were classified as high confidence, 1 as moderate, and 1 as low confidence. Because this classification was highly concentrated in one category, I adjusted the thresholds to 1% and 4% to make differences in relative margin of error more informative for this county-level dataset.\n\n\n\n## Is the margin of error bigger in small places?\n\nTo answer this we need population and our variable side by side, in the same row.\nThat means a **wide** pull.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- get_acs(\n  geography = \"county\",\n  variables = c(myvar = my_variable,\n                pop   = \"B01003_001\"),\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\",\n  output = \"wide\"\n)\n\nhead(county_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  GEOID NAME                         myvarE myvarM    popE  popM\n  <chr> <chr>                         <dbl>  <dbl>   <dbl> <dbl>\n1 06001 Alameda County, California     38.7    0.2 1651949    NA\n2 06003 Alpine County, California      41.1    4.8    1695   234\n3 06005 Amador County, California      49.9    0.6   41029    NA\n4 06007 Butte County, California       36.3    0.2  209470    NA\n5 06009 Calaveras County, California   52      0.7   45995    NA\n6 06011 Colusa County, California      35.7    0.9   21895    NA\n```\n\n\n:::\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- county_wide %>%\n  mutate(moe_pct = myvarM / myvarE * 100) %>%\n  mutate(reliability = case_when(\n    moe_pct < 1  ~ \"High confidence\",\n    moe_pct < 4 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n```\n:::\n\n\nNow compare the average population of counties in each reliability category.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide %>%\n  group_by(reliability) %>%\n  summarize(\n    n_counties = n(),\n    avg_population = mean(popE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  reliability     n_counties avg_population\n  <chr>                <int>          <dbl>\n1 High confidence         42        924758.\n2 Low confidence           4          6560.\n3 Moderate                12         31394.\n```\n\n\n:::\n:::\n\nThe high-confidence counties had an average population of 924,758, compared with 31,394 for the moderate-confidence counties and only 6,560.25 for low-confidence counties. The pattern suggests that smaller counties tend to have larger relative margins of error and less reliable estimates.\n\n## What this means for policy\n\nThe least reliable estimates came from Alpine, Sierra, Mono, and Modoc Counties. Their average population was 6,560, compared with 924,758 for the 42 high-confidence counties.\n\nThis happens because the ACS uses a sample of households. Smaller counties have fewer households in the sample, so their estimates have more uncertainty and larger margins of error.\n\nIf a state agency treated every estimate as equally reliable, these rural counties could receive less funding than they need for healthcare, transportation, housing, or services for older residents. Funding decisions should account for both the estimate and its margin of error.\n\n## My Reflections\n\nThis week helped me understand how R can be used to move from raw data to a clear result. I practiced using tidyverse functions such as `filter()`, `select()`, `mutate()`, `arrange()`, `group_by()`, and `summarize()`. Using pipes also made the code easier to follow because I could connect several steps without creating a new object after every operation.\n\nI also learned how to use `tidycensus` to download American Community Survey data. Before this, I mostly thought of Census data as a table of numbers. Working with estimates and margins of error showed me that the numbers also have different levels of reliability. In my county analysis, the smaller counties had much larger relative margins of error than the larger counties. The four low-confidence counties had an average population of 6,560, while the 42 high-confidence counties had an average population of 924,758.\n\nThe exercise also showed me why it is important to understand the structure of the data before analyzing it. I had to distinguish between long and wide formats, identify the estimate and margin-of-error columns, and make sure my reliability cutoffs were applied consistently. I am still getting used to R syntax, but the workflow is becoming clearer. The optional, non-scoring problems will require more practice because I need to build a stronger understanding of the concepts before I can work through them independently.\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}